name: Bare Run on various PHP versions

on:
    push:
        tags:
            - '*'

jobs:
    bare_run:
        runs-on: ubuntu-latest

        strategy:
            fail-fast: false
            matrix:
                php_version: ['7.2', '7.3', '7.4', '8.0']

        steps:
            -   uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php }}
                    coverage: none

            -   run: composer require symplify/easy-ci --dev --ansi
